version: '3.5'
services:
  web_server:
    build:
      context: .
      dockerfile: dockerfile
    image: 'my_nginx:1'
    command: >
      sh -c 'nginx -g "daemon off;"'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '80:80'
      - '81:81'
    networks:
      - backend
    restart: unless-stopped

  db:
    image: 'postgres:'
    command: >
      sh -c 'sleep 5000000'
    networks:
      - backend
    restart: unless-stopped

networks:
  backend: